### ISSUE TITLE
KeyError: 'following'

### ISSUE THREAD

**Issue by dreamflasher** [vindard/twitter-to-keybase#1]
I placed following.js and followers.js in the `data` folder. 
Executing python run.py yields:
```
Traceback (most recent call last):
  File "run.py", line 128, in <module>
    run()
  File "run.py", line 118, in run
    allUsernames = getTwitterUsernames() #replace this assignment if alternative Twitter list source
  File "run.py", line 106, in getTwitterUsernames
    userid = i['following']['accountId']
KeyError: 'following'
```

**Comment by vindard** [comment]
@DreamFlasher it shouldn't throw the error anymore but the code only works for one file at a time at the moment. 

I'll probably code up something a bit later to accommodate multiple files in the data dir simultaneously.
