### ISSUE TITLE
101: userID# 2816104793 failed | twitter timeout (attempt #1), please wait...

### ISSUE THREAD

**Issue by dreamflasher** [vindard/twitter-to-keybase#4]
User 1 to 100 work well, then I get `101: userID# 2816104793 failed | twitter timeout (attempt #1), please wait...` and it loops until infinity. The number of attempts needs to be limited.

**Comment by vindard** [comment]
Yes that's normal. Twitter throttles calls on their `intent` endpoint for every 100 calls and then it times out for about 30 secs (~30 attempts) and resumes.

I'll probably include something in the messaging to indicate this when it times out.

**Comment by dreamflasher** [comment]
Ah yeah that would be good to know in the output. It went to > 250 attempts and then I stopped it, assuming there is an issue.

**Comment by vindard** [comment]
@DreamFlasher fixed. The script should show a more intuitive message and a counter now. 

I've also opened a new issue (#5) for the cases where the script fails completely as with your case.

**Comment by vindard** [comment]
@DreamFlasher fixed. The script should show a more intuitive message and a counter now.

I've also opened a new issue (#5) for the cases where the script fails completely as with your case.
